version: "3.7"

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
  web:
    image: docker.pkg.github.com/belmik/zaoknom/docbox:latest
    restart: always
    command: gunicorn docbox.wsgi:application --bind 0.0.0.0:8000 --capture-output
    environment:
      - API_TOKEN
      - ALLOWED_HOSTS
      - DEBUG=False
      - DB_HOST=db
      - DB_ENGINE=django.db.backends.postgresql
      - SECRET_KEY
      - POSTGRES_PASSWORD
      - LOGIN_URL=/login/google-oauth2
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
      - SOCIAL_AUTH_GOOGLE_OAUTH2_WHITELISTED_EMAILS
      - SOCIAL_AUTH_GITHUB_KEY
      - SOCIAL_AUTH_GITHUB_SECRET
      - SOCIAL_AUTH_GITHUB_WHITELISTED_EMAILS
      - GOOGLE_SERVICE_ACCOUNT_CREDS
      - GDRIVE_BACKUP_FOLDER_ID
      - DEFAULT_PROVIDER
    depends_on:
      - db
  nginx:
    image: docker.pkg.github.com/belmik/zaoknom/nginx:latest
    restart: always
    environment:
      - PROXY_PASS_ADDRESS=web:8000
      - SSL_CERT
      - SSL_KEY
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  db:
