# Generated by Django 2.2.6 on 2019-11-03 11:08

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "address_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        default="Белгород-Днестровский",
                        max_length=64,
                        verbose_name="Насел. пункт",
                    ),
                ),
                (
                    "street_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lane", "пер."),
                            ("street", "ул."),
                            ("avenue", "п-т"),
                            ("boulevard", "б-р"),
                        ],
                        default="street",
                        max_length=16,
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=64, verbose_name="Улица")),
                ("building", models.CharField(blank=True, max_length=8, verbose_name="Дом")),
                (
                    "apartment",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Квартира"
                    ),
                ),
                (
                    "info",
                    models.TextField(blank=True, max_length=1024, verbose_name="Заметка"),
                ),
            ],
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса",},
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Имя")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер должен состоять из десяти цифр.",
                                regex="^\\d{10}$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "info",
                    models.TextField(blank=True, max_length=1024, verbose_name="Заметка"),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["name"],
                "unique_together": {("name", "phone")},
            },
        ),
        migrations.CreateModel(
            name="Mounter",
            fields=[
                (
                    "mounter_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "info",
                    models.TextField(blank=True, max_length=1024, verbose_name="Заметка"),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docbox.Client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={"verbose_name": "Монтажник", "verbose_name_plural": "Монтажники",},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "date_created",
                    models.DateField(
                        default=datetime.date.today, null=True, verbose_name="Дата оформления"
                    ),
                ),
                (
                    "provider_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Производственный номер",
                    ),
                ),
                (
                    "status",
                    models.SlugField(
                        blank=True,
                        choices=[
                            ("new", "новый"),
                            ("waiting_for_paiment", "ожидает оплаты"),
                            ("in_production", "в работе"),
                            ("delivered", "доставлен"),
                            ("mounted", "установлен"),
                            ("finished", "завершен"),
                        ],
                        default="new",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "category",
                    models.SlugField(
                        blank=True,
                        choices=[
                            ("pvc", "ПВХ изделия"),
                            ("blinds", "шторы и жалюзи"),
                            ("addons", "дополнения"),
                            ("aluminum", "алюминий"),
                            ("glass", "стеклопакеты"),
                        ],
                        default="pvc",
                        null=True,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "date_changed",
                    models.DateField(auto_now=True, null=True, verbose_name="Изменен"),
                ),
                (
                    "date_delivery",
                    models.DateField(blank=True, null=True, verbose_name="Дата доставки"),
                ),
                (
                    "date_mounting",
                    models.DateField(blank=True, null=True, verbose_name="Дата монтажа"),
                ),
                (
                    "date_finished",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закрытия заказа"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docbox.Address",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docbox.Client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "mounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docbox.Mounter",
                        verbose_name="Монтажник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "price_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Сумма заказа"
                    ),
                ),
                (
                    "provider",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Издлеия (поставщик)",
                    ),
                ),
                (
                    "delivery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Доставка",
                    ),
                ),
                (
                    "mounting",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Монтаж",
                    ),
                ),
                (
                    "added",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Дополнительные расходы",
                    ),
                ),
            ],
            options={"verbose_name": "Цена", "verbose_name_plural": "цены",},
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "provider_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
            ],
            options={"verbose_name": "Поставщик", "verbose_name_plural": "Поставщики",},
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, max_digits=10, verbose_name="Сумма"),
                ),
                ("date", models.DateField(default=datetime.date.today, verbose_name="Дата")),
                (
                    "comment",
                    models.TextField(blank=True, max_length=1024, verbose_name="Комментарий"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docbox.Client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docbox.Order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docbox.Provider",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={"verbose_name": "Транзация", "verbose_name_plural": "Транзакции",},
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="docbox.Price",
                verbose_name="Цены",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="docbox.Provider",
                verbose_name="Производитель",
            ),
        ),
    ]
