# Generated by Django 2.2.8 on 2020-01-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docbox", "0002_order_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address", old_name="info", new_name="address_info",
        ),
    ]
