# Generated by Django 2.2.8 on 2020-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docbox", "0004_transaction_cashbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cashbox",
            field=models.BooleanField(default=True, null=True, verbose_name="Касса"),
        ),
    ]
