# Generated by Django 3.1.3 on 2021-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docbox", "0007_providerorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providerorder",
            name="order_content",
            field=models.TextField(
                blank=True, default="", max_length=1024, verbose_name="Состав заказа"
            ),
        ),
        migrations.AlterField(
            model_name="providerorder",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                default=0,
                max_digits=10,
                verbose_name="Сумма заказа",
            ),
        ),
    ]
