# Generated by Django 3.1.3 on 2021-01-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbox', '0008_auto_20210106_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.SlugField(blank=True, choices=[('pvc', 'ПВХ изделия'), ('blinds', 'шторы и жалюзи'), ('addons', 'дополнения'), ('aluminum', 'алюминий'), ('glass', 'стеклопакеты'), ('steel_doors', 'стальные двери')], default='pvc', null=True, verbose_name='Категория'),
        ),
    ]
