# Generated by Django 3.1.3 on 2021-01-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docbox', '0009_auto_20210109_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='provider',
            new_name='added_expenses',
        ),
    ]
