# Generated by Django 3.1.3 on 2021-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbox', '0011_auto_20210111_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerorder',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Заказ поставщика', 'verbose_name_plural': 'Заказы поставщика'},
        ),
        migrations.AddField(
            model_name='providerorder',
            name='status',
            field=models.SlugField(blank=True, choices=[('new', 'новый'), ('waiting_for_paiment', 'ожидает оплаты'), ('in_production', 'в работе'), ('delivered', 'доставлен'), ('mounted', 'установлен'), ('finished', 'завершен')], default='new', verbose_name='Статус'),
        ),
    ]
