# Generated by Django 3.2 on 2021-04-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbox', '0012_auto_20210112_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SlugField(blank=True, choices=[('new', 'новый'), ('waiting_for_payment', 'ожидает оплаты'), ('in_production', 'в работе'), ('delivered', 'доставлен'), ('mounted', 'установлен'), ('finished', 'завершен')], default='new', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='providerorder',
            name='status',
            field=models.SlugField(blank=True, choices=[('new', 'новый'), ('waiting_for_payment', 'ожидает оплаты'), ('in_production', 'в работе'), ('delivered', 'доставлен'), ('mounted', 'установлен'), ('finished', 'завершен')], default='new', verbose_name='Статус'),
        ),
    ]
