# Generated by Django 3.2.8 on 2022-01-10 10:35

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbox', '0013_auto_20210415_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to='docbox.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Дата'),
        ),
    ]
