name: Build images

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and push image to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Build and push docbox
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/belmik/docbox:latest
      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: nginx
          push: true
          tags: ghcr.io/belmik/nginx:latest
